[package]
name = "algo"
version = "0.1.0"
authors = ["Phoenix Kahlo <phoenix@correlation-one.com>"]

[dependencies]
serde = "1.0.79"
serde_json = "1.0.31"
serde_derive = "1.0.79"
lazy_static = "1.1.0"
enum-iterator = "0.2.0"
num-traits = "0.2.6"

